version: "3"

services:
    app:
        build: ./containers/node
        container_name: awesome-movies-app
        hostname: awesome-movies-app
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
        command: npm run build

    webserver:
        build: ./containers/nginx
        container_name: awesome-movies-webserver
        hostname: awesome-movies-webserver
        depends_on:
            - app
        ports:
            - 3005:80
        volumes:
            - ./build:/var/www/html/public
        networks:
            - awesome-movies-network

networks:
    awesome-movies-network:
        driver: bridge
