version: "3"

services:
    app:
        build: ./containers/node
        container_name: awesome-movies-app-dev
        hostname: awesome-movies-app-dev
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/app
        command: npm start
        environment: 
            - CHOKIDAR_USEPOLLING=true #This is for HOT RELOAD