version: "3"

services:
    web-dev:
        build: .
        container_name: awesome-movies-web-dev
        hostname: awesome-movies-web-dev
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/app
        command: npm start
        environment: 
            - CHOKIDAR_USEPOLLING=true #This is for HOT RELOAD